### ISSUE TITLE
0.16.2 storage.upload(filename).on will throw an error!

### ISSUE THREAD

**Issue by aeroxy** [qgustavor/mega#60] opened 2020-04-08 16:34 UTC
0.16.2:

`storage.upload(filename).on(...)`

will throw an error: `storage.upload(filename)` will return undefined instead of a steamable object.

**Comment by aeroxy** [comment] 2020-04-08 16:36
TypeError: Cannot read property 'on' of undefined...

**Comment by qgustavor** [comment] 2020-04-08 18:31
Does someone posted this library somewhere? There's a lot of new issues!

[It should work](https://github.com/qgustavor/mega/blob/30f5588f4ccfae832954052b782088777859a817/test/storage.test.js#L88-L93). Can you provide a minimal, reproducible example?

**Comment by aeroxy** [comment] 2020-04-09 04:59
Well I've been using this lib for a very long time. I only came there cuz the new 0.16.2 broke my code. I think it has to do with the filenames - perhaps the filenames in production can have some issue and before 0.16.2 the lib was able to turn it into usable filenames. I am not sure. I can't reproduce the problem in the development  environment either and I can't put the code up (I already rolled back to 0.16.1) in production just so I can catch the filename...

**Comment by qgustavor** [comment] 2020-04-11 20:45
The commit that updated the library to 0.16.2 was this one: https://github.com/qgustavor/mega/commit/30f5588f4ccfae832954052b782088777859a817

There's no changes in filename handling code, it just updated URL parsing to handle new the URL format. There was also new test cases and changes in code formatting, although those don't affect filename parsing.

Because of that I think your issue wasn't caused by the update in the library but by some update in MEGA servers (that happened around the same time). Rolling back to 0.16.1 solved your problem?

**Comment by aeroxy** [comment] 2020-04-14 04:18
I have changed my upload strategy. I think it has to do with how megajs handles the `filesize` rather than the `filename` - I implemented my own methods to get `filesize` and it works with 0.16.2 as well as the newest 0.17.0...

**Comment by qgustavor** [comment] 2020-05-01 10:47
Seems it was solved! I'm closing it.

**Closed by qgustavor** 2020-05-01 10:47 UTC
