### ISSUE TITLE
Retrieve the thumbnail of a file

### ISSUE THREAD

**Issue by sal-versij** [qgustavor/mega#99] opened 2022-04-13 09:56 UTC
I'm trying to create a personal virtual-bookshelf based on books loaded on mega, I'd like to have the thumbnails that mega shows in grid mod on the official site, but I haven't found anything on megajs to do that so I tryed to search online to try with the API directily but no fortune.

Is there anything in megajs that maybe I haven't seen? or any intention to do it in the future?

**Comment by qgustavor** [comment] 2022-04-13 12:19
It is planned but not implemented yet: https://github.com/qgustavor/mega/discussions/96

You can implement it and send a pull request, at the moment I don't have time to do that.

**Comment by qgustavor** [comment] 2022-04-21 20:25
I noticed [you forked the repository](https://github.com/sal-versij/megajs). I will close this issue since it's pretty much a duplicate of #96 and wait for the pull request.

**Closed by qgustavor** 2022-04-21 20:25 UTC
