### ISSUE TITLE
Socket hangs up

### ISSUE THREAD

**Issue by SahilAggarwal2004** [qgustavor/mega#124] opened 2022-10-08 16:42 UTC
**Describe the bug**
Socket to mega hangs up and the functionality stops working until I restart the server. This error usually occurs after 2-3 hours the node server starts.

**To Reproduce**

Run this code in Node 16.13.0:

```js
const { Storage } = require("megajs")
const File = require('../models/File');

let storage;

async function initStorage() {
    storage = await new Storage({ email: process.env.MEGA_EMAIL, password: "*12-length password" }).ready
}

async function deleteFile(fileId, filename) {
    try {
        const file = storage.root.children.find(file => file.name === filename)
        await file.delete(true)
        await File.findByIdAndDelete(fileId)
        return true
    } catch { return false }
}
```

**Expected behavior**
The connection to the mega server should be made and files should be deleted when I call deleteFile() function.

**Additional context*
But Instead, the below error comes after 2-3 hours the server starts. Files delete on calling deleteFile() before encountering this error. But after this error comes, the functionality stops working.

UnhandledPromiseRejectionWarning: FetchError: request to http://w.api.mega.co.nz/6lrR3pD-IzhhnK29qXCMU-JMGW0 failed, reason: socket hang up
    at ClientRequest.<anonymous> (/opt/render/project/src/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (events.js:376:20)
    at Socket.socketOnEnd (_http_client.js:499:9)
    at Socket.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is there any way to fix this error? I am not able to find a good way. Please suggest if you know how to fix it

**Comment by qgustavor** [comment] 2022-10-08 16:51
Please follow the issue template.

**Comment by SahilAggarwal2004** [comment] 2022-10-09 05:53
Hey @qgustavor, I update the issue report according to the template.

**Comment by qgustavor** [comment] 2022-10-09 11:23
Well, the code you provided only have imports and function declarations that are never called, so if I run that code I cannot reproduce the issue the issue, which don't helps. The reasoning of providing a small example code that shows the issue is to help identify the issue.

Since you are having issues submitting this issue report I will assume the chance of it's being a bug in the library is low. The only thing I can imagine is that your MEGA session is expiring but even so I don't remember that happening with me right now.

I recommend you asking help on StackOverflow. I'm closing this with "cannot reproduce".

**Closed by qgustavor** 2022-10-09 11:23 UTC

**Comment by SahilAggarwal2004** [comment] 2022-10-09 11:46
Hey @qgustavor , sorry that I didn't provide you the whole code before. Now, I have provided you the code of the complete microservice. Can you please check what's going wrong?

**Comment by qgustavor** [comment] 2022-10-09 11:53
So you start a server, create a Storage instance and keep it open all the time. You could have simplified it a bit without the database logic, but I get it now, probably the API connection is expiring.

Try adding `keepalive: false` to the `new Storage()` constructor so it will not keep a open connection all the time or - like I do - close the connection when you are not using it. To be fair, that's that part of the code is something I never understood well since I forked the library. If it don't resolves the issue, good luck on StackOverflow.

**Comment by SahilAggarwal2004** [comment] 2022-10-09 11:56
Okay I will try to create a new connection every time I need to access the storage. Thanks for the suggestion!

**Comment by qgustavor** [comment] 2022-10-09 11:57
Remember to call `.close()` when you are not using it, otherwise it will still create connections that might expire.

**Comment by SahilAggarwal2004** [comment] 2022-10-09 11:58
Okay, thanks!
