### ISSUE TITLE
I cant import module

### ISSUE THREAD

**Issue by siftmash** [qgustavor/mega#51] opened 2019-11-29 20:22 UTC
Module not found: Error: Can't resolve 'megajs' 
`
import { File } from 'megajs';
 ngOnInit() {

        const file = File.fromURL('https://mega.nz/#!wdFElA4D!5dDMSOtGHWKVzTY6Eh2WO6SKk4oheLBpX6kntqJZ7Dc');

        file.loadAttributes((error, file) => {
            console.log(file.name) // file name
            console.log(file.size) // file size in bytes

            file.download((err, data) => {
                if (err) throw err
                console.log(data.toString()) // file contents
            })
        })

        
    }
`

**Comment by qgustavor** [comment] 2019-11-29 20:28
Well... do you installed the module?

**Comment by siftmash** [comment] 2019-11-29 20:34
YES but i use in electron and i imported in that way  import * as mega from "./mega/main.node-es"; and it's ok

**Comment by qgustavor** [comment] 2019-11-29 20:37
From the error message seems you're using Webpack, What I meant with "install" is running `npm install megajs` or `yarn add megajs`. Often you need those commands to download and install the module so you can import it.

**Comment by siftmash** [comment] 2019-11-29 20:46
Yeah I know but import from node_modules doesn't work correctly maybe only in my case :)

**Comment by qgustavor** [comment] 2019-11-29 22:05
Seems there is something wrong with your module loader. I tried to find some kind of test website and I got this: https://codesandbox.io/s/ecstatic-tree-3hun4

Other modules are working fine? Consider importing the CommonJS version if you're not planning to use tree shaking.

**Comment by qgustavor** [comment] 2019-11-30 23:01
As there was no reply I will close this issue with the old "could not reproduce".

**Closed by qgustavor** 2019-11-30 23:01 UTC
