### ISSUE TITLE
Error when trying to use Storage

### ISSUE THREAD

**Issue by bodabaker** [qgustavor/mega#92] opened 2022-03-11 12:13 UTC
When trying to create `const storage` like so:
```javascript
import { Storage } from 'https://cdn.skypack.dev/megajs@1'

const storage = new Storage({
  email: 'user@example.com',
  password: 'pass',
  userAgent: null,
}).ready;
```
It gives this error:
```
Uncaught (in promise) RangeError: Trying to access beyond buffer length
    M https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:612
    readInt32BE https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:688
    Cn https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:3906
    a https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:4917
    login https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:4945
    k https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:3856
    promise callback*k https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:3856
    request https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:4324
    login https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:4941
    Fr https://cdn.skypack.dev/-/megajs@v1.0.2-FZJ4eiVfK38KPhR7DiZq/dist=es2019,mode=imports/optimized/megajs.js:4899
    <anonymous> http://127.0.0.1:5555/app.js:3
megajs.js:612:13
```

**Comment by qgustavor** [comment] 2022-03-11 13:25
You missed the `àwait` since `.ready` is a promise that returns the `Storage` object. But, even so, that should not throw a `RangeError`.

Could not reproduce this error: https://replit.com/@qgustavor/megajs-issue-92#index.ts

**Comment by qgustavor** [comment] 2022-03-11 13:41
From your stack trace seems the error got thrown [in the password derivation function](https://github.com/qgustavor/mega/blob/292520fc61b4e6c04a0ab02a6e226ac95ab43e95/browser/aes.mjs#L14), so looks like I could not reproduce this issue because the password in the example code is not the password that's causing this issue.

Since this code is almost the same thing as [tonistiigi's code](https://github.com/tonistiigi/mega/blob/eb2c8fc639ee7affb3c3d4811bad200c7d4d8a92/lib/crypto/index.js#L35), the only changes being stylistic changes, it should work pretty well... should, but looks like that is [this issue](https://github.com/tonistiigi/mega/issues/43).

As you can check this code depends mostly on the password length. What is the length of password which is causing this issue for you? As you can see [here](https://github.com/qgustavor/mega/blob/292520fc61b4e6c04a0ab02a6e226ac95ab43e95/test/prepareKey.test.mjs) currently test code checks for passwords with 8 byte length and 64 byte length, so maybe you found some edge case this code is not handling well.

**Comment by bodabaker** [comment] 2022-03-11 14:01
@qgustavor yeah that was just an example. My password is actually 10 characters so I'm gonna shorten it later and see if works

**Comment by qgustavor** [comment] 2022-03-11 14:10
Maybe it was a bad idea to make the test code test only multiples of 16 bytes. The fix is simple: instead of `if (i + j < password.length) {` it's just `if (i + j < password.length - 3) {`. I will add a test case too.

**Comment by qgustavor** [comment] 2022-03-11 14:29
I just a noticed a non-stylistic change in the code: tonistiigi's code is `a.readInt32BE(i+j, true)`. This second argument is a deprecated `noAssert` argument that was removed in Node v10.0.0. Fixing the condition is better than using `true`.

megajs@1.0.3 was been released. I will close this issue.

**Closed by qgustavor** 2022-03-11 14:29 UTC
